# Generated by Django 5.2.6 on 2025-09-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_agent_voicesession_turn_safetyalert_emotionsession"),
    ]

    operations = [
        # Remove EmotionData table
        migrations.DeleteModel(
            name="EmotionData",
        ),
        # Note: EmotionSession model is kept for therapy sessions in ai_service
    ]
