# Generated by Django 5.2.6 on 2025-09-27 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_emotion_ml_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en-IN", "English (India)"),
                            ("hi-IN", "Hindi (India)"),
                            ("ta-IN", "Tamil (India)"),
                        ],
                        default="en-IN",
                        max_length=10,
                    ),
                ),
                ("dark_mode", models.BooleanField(default=False)),
                ("notifications", models.BooleanField(default=True)),
                ("consent_store_transcripts", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
