# Generated by Django 4.2.25 on 2025-11-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotionsession",
            name="angry",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="emotionsession",
            name="disgusted",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="emotionsession",
            name="fearful",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="emotionsession",
            name="sad",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="emotionsession",
            name="surprised",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="emotionsession",
            name="anxious",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="emotionsession",
            name="happy",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="emotionsession",
            name="neutral",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="emotionsession",
            name="stressed",
            field=models.FloatField(default=0.0),
        ),
    ]
